version: '3'
services:
    php-apache-cpp:
        build:
            context: ./
            dockerfile: Dockerfile-apache.dev
        ports:
            - 80:80
        volumes:
            - ./:/var/www:z
        links:
            - 'mariadb-cpp'

    mariadb-cpp:
        image: mariadb:10.1
        volumes:
            - mariadb-cpp:/var/lib/mysql
        environment:
            TZ: "America/New_York"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'

volumes:
    mariadb-cpp: